### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by will-meng** [will-meng/my-map-run#1]
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, actions, reducer
- [ ] Presentational Components
- [ ] Styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds

**Comment by chungkikelly** [comment]
Really well done user authentication. 

A couple notes: the login / signup button on the top right corner of each of the forms misled me initially into thinking that the form was the other form. A conventional way to handle the feature of switching between forms is just to have a link with a message at the bottom of the form (e.g. `Already have an account?`). 

The session form error handling is the best I've seen done during FSP. Well done.

**Comment by will-meng** [comment]
Added those tiny messages, hope it helps
